print("EPIC: The Musica")
print("The Horse and the Infant:")
print(" ")
print("Odysseus:")
print("Alright my brothers listen clostly")
print("Tonight we make the Trojans pay")
print("10 years of war they killed us slowly")
print("but now we'll be the ones who slay")
print("think of your wives and your children")
print("Your family's wondering where you've been")
print("Their growing old and yet you're still here")
print("do what I say and you'll see them again")
print(" ")
print("Crew members:")
print("Yes sir")
print(" ")
print("Odysseus:")
print("Diomedes will lead the charge")
print("Agamemnon will flank the guards")
print("Menelaus will let our mates")
print("Through the gates to take the whole city at large")
print("Teucer will shoot any ambush attack")
print("And little Ajax will stay back")
print("Nestor, secure Helen and protect her")
print("Neo, avenge your father, kill the brothers of Hector")
print(" ")
print("Crew members:")
print("yes sir!")
print(" ")
print("Odysseus:")
print("Find that inner strength now  ")
print(" ")
print("crew members:")
print("whoo!")
print(" ")
print("Odysseus:")
print("Use that well of pride ")
print(" ")
print("crew members:")
print("whoo!")
print(" ")
print("Odysseus:")
print("Fight through every pain now")
print("...")
print(" ")

