one = input("write a weird noun: ")
two = input("write a verb ending in -ing: ")
three = input("name a silly adjective: ")
four = input("name a food: ")
five = input("write a quantity: ")
six = input("Name a famous person: ")
seven = input ("Write a funky noise: ")

print(one)
print(two)
print(three)
print(four)
print(five)
print(six)
print(seven)

print("  ")
print("  ")

print("there was a human named " + six + ".")
print("one day, " + six + " came across a " + one + ".")
print("The " + one + " fed " + six + " " + five + " " + four)
print("But... The " + five + " " + four + " was poisoned!")
print(six + " screamed")
print(seven)
print(six + " was " + two )
print(seven)
print(seven)
print("yea...")
print("then..." + six + " died and then the " + one + " decided to be " + three + " and ate " + six)
print("The end :)")